### ISSUE TITLE
Minor styling issue

### ISSUE THREAD

**Issue by vittolewerissa** [Salies/nihilanth-ghost-theme#1]
Hi I really like the theme,
but it appears there's minor issue on the styling, `h3` header needs a little push downwards :)
<img width="824" alt="screen shot 2017-01-04 at 1 29 59 pm" src="https://cloud.githubusercontent.com/assets/15160023/21633450/ecb8daf2-d281-11e6-897d-ed314b541ae3.png">

I guess the `<p>` has no `margin-bottom`, but it occurs only on the homepage, not when you access a post.

Keep up the work. Thanks :)

**Comment by vittolewerissa** [comment]
Fix on #2

**Comment by Salies** [comment]
close
